global using System.Text;
global using Microsoft.IdentityModel.Tokens;
global using System.IdentityModel.Tokens.Jwt;
global using System.Security.Claims;
global using System.Security.Cryptography;
global using System.Data;
global using System.Data.SqlClient;
global using System.Reflection;
global using System.Text.RegularExpressions;